#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8093/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================

  # ===============================
  # JPA / HIBERNATE
  # ===============================
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
Feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"