spring:
  application:
    name: skyblue-administrator
server:
  port: 8099
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
